#!/bin/bash

VERSION=3.697
PACKAGE=phylip-suite
TOOL=consense
DIRECTORY=.

PERSISTENT_FILE_STORAGE=/ocean
if [ -d $PERSISTENT_FILE_STORAGE ]; then
        OPTIONS="-B $PERSISTENT_FILE_STORAGE"
fi

if [ -d /local ]; then
        OPTIONS=$OPTIONS" -B /local"
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
